package cn.onboard.android.app.cache;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE.
 */
public class Cache {

    /** Not-null value. */
    private String url;
    private String data;

    public Cache() {
    }

    public Cache(String url, String data) {
        this.url = url;
        this.data = data;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
